USE [DM_PP]
GO

/****** Object:  View [dbo].[entradas]    Script Date: 03/09/2023 19:42:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[entradas]
AS

SELECT		DW.va4.MSEG.MATNR, 
			DW.va4.MSEG.EBELN, 
			DW.va4.MSEG.EBELP, 
			SUM(DW.va4.MSEG.MENGE) AS SumOfMENGE, 
			DW.va4.MSEG.MEINS, 
			DW.va4.MSEG.LGORT AS ALMACEN, 
			DW.va4.MARA.MATKL

FROM            DW.va4.MSEG INNER JOIN
					DW.va4.MARA 
						ON DW.va4.MSEG.MANDT = DW.va4.MARA.MANDT AND 
						   DW.va4.MSEG.MATNR = DW.va4.MARA.MATNR

GROUP BY	DW.va4.MSEG.MATNR, DW.va4.MSEG.EBELN, DW.va4.MSEG.EBELP, DW.va4.MSEG.MEINS, 
			DW.va4.MSEG.LGORT, DW.va4.MSEG.MANDT, DW.va4.MARA.PRDHA, DW.va4.MARA.MATKL

HAVING      (DW.va4.MSEG.EBELP <> '00000') AND 
			(DW.va4.MSEG.MANDT = '040') AND 
			(DW.va4.MARA.PRDHA = '00100') AND 
			(DW.va4.MARA.MATKL = '40000' OR
				DW.va4.MARA.MATKL = '40001')

GO