USE [DM_PP]
GO

/****** Object:  View [dbo].[venta_pendiente]    Script Date: 03/09/2023 20:57:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[venta_pendiente]
AS

SELECT		CONVERT(NUMERIC(20, 0), DW.va4.VBAK.VBELN) AS PEDIDO, 
			DW.va4.KNA1.NAME1 AS CLIENTE, 
			DW.va4.KNA1.KUNNR AS COD_CLIENTE, 
			DW.va4.VBAP.MATNR AS COD_MATERIAL, 
			DW.va4.MAKT.MAKTG AS MATERIAL, 
			DW.va4.VBAP.UMZIZ / DW.va4.VBAP.UMZIN * DW.va4.VBAP.KWMENG AS CANTIDAD, 
			DW.va4.VBAP.MEINS AS UNIDAD

FROM        DW.va4.VBAK INNER JOIN
				DW.va4.VBAP 
					ON DW.va4.VBAK.VBELN = DW.va4.VBAP.VBELN AND DW.va4.VBAK.MANDT = DW.va4.VBAP.MANDT INNER JOIN
                DW.va4.VBBE 
					ON DW.va4.VBAP.POSNR = DW.va4.VBBE.POSNR AND DW.va4.VBAP.VBELN = DW.va4.VBBE.VBELN AND 
					   DW.va4.VBAP.MANDT = DW.va4.VBBE.MANDT INNER JOIN
                DW.va4.KNA1 
					ON DW.va4.KNA1.MANDT = DW.va4.VBAP.MANDT AND DW.va4.VBAK.KUNNR = DW.va4.KNA1.KUNNR INNER JOIN
                DW.va4.MAKT 
					ON DW.va4.VBAP.MATNR = DW.va4.MAKT.MATNR AND DW.va4.VBAP.MANDT = DW.va4.MAKT.MANDT

WHERE       (DW.va4.MAKT.SPRAS = 'S') AND 
			(DW.va4.VBAP.MATKL = '40000' OR DW.va4.VBAP.MATKL = '40001')

GO